scene:
  name: scene_kitchen_prep_se3_me_optimized
  objects:
  - half_extents:
    - 0.12
    - 0.08
    - 0.01
    mujoco_name: cutting_board
    short_name: cutting_board
  - half_extents:
    - 0.028
    - 0.028
    - 0.028
    mujoco_name: apple
    position:
    - 0.39870145972323207
    - -0.11193882716103724
    - 0.98
    short_name: apple
    yaw: 0.0
  - half_extents:
    - 0.027
    - 0.027
    - 0.055
    mujoco_name: can
    position:
    - 0.3764593835064397
    - 0.4427330916019067
    - 0.997
    short_name: can
    yaw: -2.3161794805449105
  - half_extents:
    - 0.025
    - 0.025
    - 0.04
    mujoco_name: bottle
    position:
    - 0.7186133370551715
    - 0.20604859060385414
    - 0.982
    short_name: bottle
    yaw: 1.8777450609239015
  - half_extents:
    - 0.05
    - 0.025
    - 0.02
    mujoco_name: sponge
    short_name: sponge
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
