scene:
  name: scene_desk_se3_optimized
  objects:
  - half_extents:
    - 0.028
    - 0.028
    - 0.055
    mujoco_name: mug
    position:
    - 0.36735584416402833
    - 0.39164687026691314
    - 0.997
    short_name: mug
    yaw: 0.955763647366249
  - half_extents:
    - 0.075
    - 0.05
    - 0.015
    mujoco_name: book
    short_name: book
  - half_extents:
    - 0.035
    - 0.0075
    - 0.075
    mujoco_name: phone
    short_name: phone
  - half_extents:
    - 0.025
    - 0.025
    - 0.05
    mujoco_name: pen_cup
    position:
    - 0.3774780095208401
    - -0.06235809649145872
    - 0.992
    short_name: pen_cup
    yaw: -1.4128025802311974
  - half_extents:
    - 0.025
    - 0.02
    - 0.015
    mujoco_name: stapler
    position:
    - 0.7629124224676531
    - 0.16428877268400502
    - 0.957
    short_name: stapler
    yaw: 0.0
  - half_extents:
    - 0.028
    - 0.028
    - 0.07
    mujoco_name: vase
    short_name: vase
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
