scene:
  name: scene_cluttered_se3_me_optimized
  objects:
  - half_extents:
    - 0.025
    - 0.02
    - 0.025
    mujoco_name: red_block
    position:
    - 0.7035565212748619
    - -0.3654431738484069
    - 0.967
    short_name: red_block
    yaw: 0.0
  - half_extents:
    - 0.02
    - 0.025
    - 0.03
    mujoco_name: blue_block
    position:
    - 0.655562518112461
    - 0.4148523409733934
    - 0.972
    short_name: blue_block
    yaw: 0.0
  - half_extents:
    - 0.025
    - 0.025
    - 0.05
    mujoco_name: green_cylinder
    position:
    - 0.529538856858775
    - 0.43688996132134067
    - 0.992
    short_name: green_cylinder
    yaw: 0.0
  - half_extents:
    - 0.025
    - 0.015
    - 0.04
    mujoco_name: yellow_block
    position:
    - 0.5679640357923309
    - -0.3940936970052319
    - 0.982
    short_name: yellow_block
    yaw: 0.0
  - half_extents:
    - 0.02
    - 0.02
    - 0.045
    mujoco_name: orange_cylinder
    position:
    - 0.35113678074045346
    - -0.15303516996541391
    - 0.987
    short_name: orange_cylinder
    yaw: 0.0
  - half_extents:
    - 0.02
    - 0.02
    - 0.035
    mujoco_name: purple_block
    position:
    - 0.7991284935035603
    - 0.381102118677414
    - 0.977
    short_name: purple_block
    yaw: 0.0
  - half_extents:
    - 0.027
    - 0.027
    - 0.04
    mujoco_name: white_cylinder
    position:
    - 0.776855050322325
    - 0.15109422204781048
    - 0.982
    short_name: white_cylinder
    yaw: 0.0
  - half_extents:
    - 0.022
    - 0.018
    - 0.03
    mujoco_name: pink_block
    position:
    - 0.8050505470845495
    - -0.20132216258863692
    - 0.972
    short_name: pink_block
    yaw: 0.0
  - det_id: -1
    half_extents:
    - 0.1
    - 0.08
    - 0.01
    mujoco_name: tray_left
    short_name: tray_left
  - det_id: -1
    half_extents:
    - 0.1
    - 0.08
    - 0.01
    mujoco_name: tray_right
    short_name: tray_right
  - det_id: -1
    half_extents:
    - 0.06
    - 0.06
    - 0.03
    mujoco_name: bin_center
    short_name: bin_center
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
