scene:
  name: scene_kitchen_prep_se3_me_optimized
  objects:
  - half_extents:
    - 0.12
    - 0.08
    - 0.01
    mujoco_name: cutting_board
    short_name: cutting_board
  - half_extents:
    - 0.028
    - 0.028
    - 0.028
    mujoco_name: apple
    position:
    - 0.3696591721154948
    - -0.07413070916241091
    - 0.98
    short_name: apple
    yaw: 0.0
  - half_extents:
    - 0.027
    - 0.027
    - 0.055
    mujoco_name: can
    position:
    - 0.6742352151073316
    - 0.20290502275709002
    - 0.997
    short_name: can
    yaw: -0.7539675359338923
  - half_extents:
    - 0.025
    - 0.025
    - 0.095
    mujoco_name: bottle
    position:
    - 0.3532201613371592
    - 0.36872522071799496
    - 1.037
    short_name: bottle
    yaw: 0.007075093363331038
  - half_extents:
    - 0.05
    - 0.025
    - 0.02
    mujoco_name: sponge
    short_name: sponge
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
