scene:
  name: scene_breakfast_optimized
  objects:
  - half_extents:
    - 0.08
    - 0.08
    - 0.04
    mujoco_name: bowl_0_a430d997_0564_4fae_801b_c01693feeee6
    short_name: bowl
  - half_extents:
    - 0.035
    - 0.023
    - 0.08
    mujoco_name: cereal_0_1cd24fb39eb340b28b7a0ce00e6d3c6a
    short_name: cereal
  - half_extents:
    - 0.08
    - 0.08
    - 0.005
    mujoco_name: napkin_0_d147f73d5f2249a7ba169a1cf0c21e95
    short_name: napkin
  - half_extents:
    - 0.075
    - 0.015
    - 0.01
    mujoco_name: spoon_0_98c9fc6a50414f68979318c693fe25f8
    short_name: spoon
  - half_extents:
    - 0.09
    - 0.02
    - 0.025
    mujoco_name: banana_0_cfd0a5186de3408cbb6fbde0cd6144ce
    short_name: banana
  - half_extents:
    - 0.04
    - 0.04
    - 0.11
    mujoco_name: milk_carton_0_8ce748cf2f4a410181650550275650b1
    short_name: milk_carton
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
