scene:
  name: scene_meal_assembly_se3_me_optimized
  objects:
  - half_extents:
    - 0.08
    - 0.08
    - 0.04
    mujoco_name: bowl
    short_name: bowl
  - half_extents:
    - 0.12
    - 0.08
    - 0.01
    mujoco_name: cutting_board
    short_name: cutting_board
  - half_extents:
    - 0.086
    - 0.023
    - 0.04
    mujoco_name: cereal
    position:
    - 0.48444788841625547
    - 0.010356140876066046
    - 0.955
    short_name: cereal
    yaw: 0.0
  - half_extents:
    - 0.09
    - 0.02
    - 0.025
    mujoco_name: banana
    position:
    - 0.7375761018412436
    - 0.07075778958506967
    - 0.94
    short_name: banana
    yaw: 0.0
  - half_extents:
    - 0.028
    - 0.028
    - 0.028
    mujoco_name: apple
    position:
    - 0.4464764701890831
    - 0.41654509918788657
    - 0.98
    short_name: apple
    yaw: 0.0
  - half_extents:
    - 0.027
    - 0.027
    - 0.055
    mujoco_name: can
    position:
    - 0.5741848942791096
    - -0.07837430544626138
    - 0.997
    short_name: can
    yaw: -0.8411947009472399
  - half_extents:
    - 0.025
    - 0.025
    - 0.04
    mujoco_name: bottle
    position:
    - 0.3758703809972578
    - -0.06626542956045658
    - 0.982
    short_name: bottle
    yaw: 0.5587532278772986
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
