scene:
  name: scene_meal_assembly_se3_optimized
  objects:
  - half_extents:
    - 0.08
    - 0.08
    - 0.04
    mujoco_name: bowl
    short_name: bowl
  - half_extents:
    - 0.12
    - 0.08
    - 0.01
    mujoco_name: cutting_board
    short_name: cutting_board
  - half_extents:
    - 0.086
    - 0.023
    - 0.153
    mujoco_name: cereal
    position:
    - 0.8156200893223285
    - -0.2273355033248663
    - 1.068
    short_name: cereal
    yaw: 0.0
  - half_extents:
    - 0.09
    - 0.02
    - 0.025
    mujoco_name: banana
    position:
    - 0.35105691142380235
    - -0.22046878589317204
    - 0.94
    short_name: banana
    yaw: 0.0
  - half_extents:
    - 0.028
    - 0.028
    - 0.028
    mujoco_name: apple
    position:
    - 0.7608593305572867
    - -0.3767024025321007
    - 0.98
    short_name: apple
    yaw: 0.0
  - half_extents:
    - 0.027
    - 0.027
    - 0.055
    mujoco_name: can
    position:
    - 0.40062188301235435
    - 0.43718038788065317
    - 0.997
    short_name: can
    yaw: 0.0
  - half_extents:
    - 0.025
    - 0.025
    - 0.095
    mujoco_name: bottle
    position:
    - 0.7374268904328346
    - 0.18951436718925835
    - 1.037
    short_name: bottle
    yaw: -2.4135375340689933
  table:
    half_extents:
    - 0.4
    - 0.7
    - 0.027
    pos_world:
    - 0.6
    - 0.0
    - 0.915
