tasks:
    - object_indices: [0, 1]  # black tea or chai
    - object_indices: [2, 3, 4]  # milk, panda cookies, or ritz crackers

objects:
    - "black tea"
    - "chai" 
    - "milk"
    - "panda cookies"
    - "ritz crackers"

# colors are used for plotting on a 2D grid
colors:
    - "black"
    - "orange" 
    - "purple"
    - "brown"
    - "yellow"

object_positions:
    - [0.5, -0.3, 0.0]  # black tea
    - [0.3, 0.2, 0.0]   # chai
    - [0.4, -0.2, 0.0]  # milk
    - [0.7, 0.3, 0.0]   # panda cookies
    - [0.5, 0.4, 0.0]   # ritz crackers

movable_object_mask: [1, 1, 1, 1, 1]

box_sizes:
    - [0.22, 0.14]  # black tea
    - [0.15, 0.076] # chai
    - [0.15, 0.15]  # milk
    - [0.18, 0.12]  # panda
    - [0.15, 0.15]  # ritz